apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: 314146301712.dkr.ecr.us-west-1.amazonaws.com/authentication-service:latest
          ports:
            - containerPort: 3001
      imagePullSecrets:
        - name: ecr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
