services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/config.env
    networks:
      - health-sync-network
  
  authentication-service:
    container_name: authentication-service
    build:
      context: ./authentication-service
    ports:
      - "3001:3001"
    env_file:
      - ./authentication-service/config.env
    networks:
      - health-sync-network

  patient-record-service:
    container_name: patient-record-service
    build:
      context: ./patient-record-service
    ports:
      - "3002:3002"
    env_file:
      - ./patient-record-service/config.env
    networks:
      - health-sync-network
  
  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
    ports:
      - "3003:3003"
    env_file:
      - ./notification-service/config.env
    networks:
      - health-sync-network

  appointment-service:
    container_name: appointment-service
    build:
      context: ./appointment-service
    ports:
      - "3004:3004"
    env_file:
      - ./appointment-service/config.env
    depends_on:
      - patient-record-service
      - notification-service
      - doctor-service
    networks:
      - health-sync-network
  
  doctor-service:
    container_name: doctor-service
    build:
      context: ./doctor-service
    ports:
      - "3005:3005"
    env_file:
      - ./doctor-service/config.env
    networks:
      - health-sync-network

  report-service:
    container_name: report-service
    build:
      context: ./report-service
    ports:
      - "3007:3007"
    env_file:
      - ./report-service/config.env
    networks:
      - health-sync-network

networks:
  health-sync-network:
    driver: bridge