services:
  authentication-service:
    build:
      context: ./authentication-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - health-sync-network

  patient-record-service:
    build:
      context: ./patient-record-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DB_HOST=patient-record-db
      - DB_PORT=5432
      - DB_USER=patient-user
      - DB_PASSWORD=password
      - DB_NAME=patient_db
    depends_on:
      - patient-record-db
    networks:
      - health-sync-network

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DB_HOST=notification-db
      - DB_PORT=5432
      - DB_USER=notification-user
      - DB_PASSWORD=password
      - DB_NAME=notification_db
    depends_on:
      - notification-db
    networks:
      - health-sync-network

  patient-record-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: patient-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patient_db
    volumes:
      - patient-db-data:/var/lib/postgresql/data
    networks:
      - health-sync-network
    ports:
      - "5434:5432"

  notification-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: notification-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    networks:
      - health-sync-network
    ports:
      - "5435:5432"

volumes:
  auth-db-data:
  patient-db-data:
  notification-db-data:

networks:
  health-sync-network:
    driver: bridge