apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
        - name: patient-record-service
          image: 314146301712.dkr.ecr.us-west-1.amazonaws.com/patient-record-service:latest
          ports:
            - containerPort: 3002
      imagePullSecrets:
        - name: ecr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
