apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-record-service
  template:
    metadata:
      labels:
        app: patient-record-service
    spec:
      containers:
        - name: patient-record-service
          image: patient-record-service
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: microservices-config
---
apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
