name: Deploy to EKS

on:
  workflow_run:
    workflows:
      - Build and Push Docker Images to ECR
    types:
      - completed

jobs:
  deploy-to-eks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Update kubeconfig for EKS
      - name: Update kubeconfig
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name health-sync-cluster

      # Step 4: Apply Kubernetes manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f config-map.yaml
          kubectl apply -f api-gateway-deployment.yaml
          kubectl apply -f appointment-deployment.yaml
          kubectl apply -f authentication-deployment.yaml
          kubectl apply -f doctor-deployment.yaml
          kubectl apply -f notification-deployment.yaml
          kubectl apply -f patient-record-deployment.yaml
          kubectl apply -f report-deployment.yaml
