name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment for linting and testing
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install dependencies for each microservice
      - name: Install dependencies for authentication-service
        run: |
          cd authentication-service
          npm install

      - name: Install dependencies for patient-record-service
        run: |
          cd patient-record-service
          npm install

      - name: Install dependencies for notification-service
        run: |
          cd notification-service
          npm install

      - name: Install dependencies for appointment-service
        run: |
          cd appointment-service
          npm install

      - name: Install dependencies for doctor-service
        run: |
          cd doctor-service
          npm install

      # Step 4: Run Linting (Optional)
      - name: Run Linting for authentication-service
        run: |
          cd authentication-service
          npm run lint

      - name: Run Linting for patient-record-service
        run: |
          cd patient-record-service
          npm run lint

      - name: Run Linting for notification-service
        run: |
          cd notification-service
          npm run lint

      - name: Run Linting for appointment-service
        run: |
          cd appointment-service
          npm run lint

      - name: Run Linting for doctor-service
        run: |
          cd doctor-service
          npm run lint

      # Step 5: Run Tests (Optional)
      - name: Run Tests for authentication-service
        run: |
          cd authentication-service
          npm test

      - name: Run Tests for patient-record-service
        run: |
          cd patient-record-service
          npm test

      - name: Run Tests for notification-service
        run: |
          cd notification-service
          npm test

      - name: Run Tests for appointment-service
        run: |
          cd appointment-service
          npm test

      - name: Run Tests for doctor-service
        run: |
          cd doctor-service
          npm test

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build and push Docker images
      - name: Build and push Docker images
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          SERVICES=("authentication-service" "patient-record-service" "notification-service" "appointment-service" "doctor-service" "api-gateway")
          for SERVICE in "${SERVICES[@]}"
          do
            docker build -t $ECR_REPOSITORY_URL/$SERVICE:$IMAGE_TAG ./$SERVICE
            docker push $ECR_REPOSITORY_URL/$SERVICE:$IMAGE_TAG
          done
        env:
          ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
